// THE CLAUDE ROUTER, WITHOUT A TERMINAL.
//
// Same prompt, same parser, same failsafe. What changes is the transport, and
// with it an entire class of bug — because the old one drove an interactive TUI
// through a PTY, which is a keyboard emulator:
//
//   * a 16KB prompt landed as a PASTE that sits one Enter short of submitting,
//     so we slept 450ms and sent \r and hoped. When the timing slipped the
//     Enter submitted an empty line, and the model said so out loud:
//     "both of your messages so far were empty (no content came through)".
//   * `/clear` was written the same way and never submitted at all, so context
//     never cleared and routing slowed from 15.9s to 24.0s across two turns.
//   * the trust dialog listed "No, exit" FIRST, so a stray Enter killed the
//     session; Enter is not \r anyway (kitty keyboard protocol).
//   * with no clean stdout, the answer had to come back through a FILE.
//
// None of that exists here. stdin is a PIPE: one newline-delimited JSON object
// is one message by framing, not by keystroke timing. There is nothing to
// confirm, nothing to poll, nothing to scrape out of escape sequences.
//
// MEASURED before it was written (28 Aug), because guessing is what produced
// the bugs above. Three routes down one warm process: 9.1s / 2.0s / 5.5s,
// against 15.9s and 24.0s on the PTY path — and the schema held every time.
//
// A PRIVATE, STDIO MCP SERVER
// ---------------------------
// The tool lives in a node process this engine spawns and owns, reachable only
// over that pipe. The alternative — a `router` principal on Unmute's shared
// HTTP MCP server — would have put a task-creating surface on a port, and the
// invariant that task sessions cannot touch the wall is worth more than the
// few lines it saves. Nothing but this engine can reach this tool.
//
// THE TOOLSEARCH HOP, which cost three failed spike runs to find: the tool is
// DEFERRED — the model must call ToolSearch to load its schema before it can
// call it. A prompt that says "reply ONLY by calling the tool, do nothing else"
// forbids exactly that, and the route then silently never happens. So the
// prompt permits it, and warm() pays for it ONCE per process (that is the
// difference between the 9.1s first turn and the 2.0s second).

import { spawn, type ChildProcess } from 'node:child_process'
import { promises as fs } from 'node:fs'
import { join } from 'node:path'
import { homedir } from 'node:os'
import { createLogger } from './log'
import { routeDecisionTool, compactDecision, ROUTE_TOOL_NAME, type DecisionSchemaOpts } from './router-decision-schema'

const log = createLogger('headless-router')

/** Fully-qualified name Claude gives an MCP tool: mcp__<server>__<tool>. */
const SERVER = 'unmute_router'
export const QUALIFIED_TOOL = `mcp__${SERVER}__${ROUTE_TOOL_NAME}`

export interface HeadlessRouterOpts {
  model?: string
  /** Where the generated MCP server + config are written. */
  dir?: string
  /** Respawn after this many decisions, to cap context growth. */
  recycleEvery?: number
  /** Test seam. */
  spawnFn?: typeof spawn
  execPath?: string
}

/**
 * The one-tool MCP server, written to disk at warm() time.
 *
 * Generated rather than shipped as a file because the app is packaged into an
 * asar, which an external node process cannot execute out of. It is ~40 lines
 * and has no dependencies, so generating it is cheaper than unpacking it.
 *
 * It does NOT need to do anything with the arguments: the decision is read off
 * the CLI's own event stream (a `tool_use` block on stdout), not from here.
 * This server exists purely to put a JSON Schema in front of the model. Its
 * stderr never reaches us — it is the CLI's child, not ours, which cost one
 * spike run to discover.
 */
function serverSource(tool: ReturnType<typeof routeDecisionTool>): string {
  return `// Generated by Unmute. One schema'd tool; the decision is read from the CLI stream.
const TOOL = ${JSON.stringify(tool, null, 2)}
const send = (o) => process.stdout.write(JSON.stringify(o) + '\\n')
let buf = ''
process.stdin.on('data', (d) => {
  buf += d
  let i
  while ((i = buf.indexOf('\\n')) >= 0) {
    const line = buf.slice(0, i); buf = buf.slice(i + 1)
    if (!line.trim()) continue
    let m; try { m = JSON.parse(line) } catch { continue }
    if (m.method === 'initialize') {
      send({ jsonrpc: '2.0', id: m.id, result: {
        protocolVersion: (m.params && m.params.protocolVersion) || '2024-11-05',
        capabilities: { tools: {} },
        serverInfo: { name: '${SERVER}', version: '1.0.0' },
      } })
    } else if (m.method === 'tools/list') {
      send({ jsonrpc: '2.0', id: m.id, result: { tools: [TOOL] } })
    } else if (m.method === 'tools/call') {
      send({ jsonrpc: '2.0', id: m.id, result: { content: [{ type: 'text', text: 'recorded' }] } })
    } else if (m.id !== undefined) {
      send({ jsonrpc: '2.0', id: m.id, result: {} })
    }
  }
})
`
}

export class HeadlessRouterEngine {
  /** Declared to the Router so the prompt asks for a TOOL CALL and, crucially,
   *  stops telling the model "no tools" — which would forbid loading this one. */
  readonly answerTool = QUALIFIED_TOOL
  private child: ChildProcess | null = null
  private buf = ''
  /** Decisions seen on the stream, oldest first; decide() takes the next one. */
  private calls: unknown[] = []
  private taken = 0
  private ready = false
  private decisions = 0
  private starting: Promise<void> | null = null
  private readonly dir: string
  private readonly o: Required<Omit<HeadlessRouterOpts, 'spawnFn' | 'execPath' | 'dir'>> & Pick<HeadlessRouterOpts, 'spawnFn' | 'execPath'>

  constructor(opts: HeadlessRouterOpts = {}, private readonly schemaOpts: DecisionSchemaOpts = { ops: true }) {
    this.dir = opts.dir ?? join(homedir(), '.unmute', 'remote', 'router-headless')
    this.o = {
      model: opts.model ?? 'sonnet',
      recycleEvery: opts.recycleEvery ?? 40,
      spawnFn: opts.spawnFn,
      execPath: opts.execPath,
    }
  }

  /** Bring a process up AND load the tool schema into it, so the first real
   *  route does not pay the ToolSearch hop. Idempotent and single-flighted. */
  warm(): Promise<void> {
    if (this.ready && this.child && !this.child.killed) return Promise.resolve()
    if (this.starting) return this.starting
    this.starting = this.start().catch((e) => {
      log.warn('headless router failed to warm', { error: (e as Error).message })
    }).finally(() => { this.starting = null })
    return this.starting
  }

  private async start(): Promise<void> {
    await fs.mkdir(this.dir, { recursive: true })
    const serverPath = join(this.dir, 'router-mcp.mjs')
    const cfgPath = join(this.dir, 'mcp.json')
    const exec = this.o.execPath ?? process.execPath
    await fs.writeFile(serverPath, serverSource(routeDecisionTool(this.schemaOpts)))
    await fs.writeFile(cfgPath, JSON.stringify({
      mcpServers: {
        [SERVER]: {
          command: exec,
          args: [serverPath],
          // Electron's binary IS node when this is set; a packaged build has no
          // system node to rely on.
          env: { ELECTRON_RUN_AS_NODE: '1' },
        },
      },
    }))

    const sp = this.o.spawnFn ?? spawn
    const child = sp('claude', [
      '-p',
      '--input-format', 'stream-json',
      '--output-format', 'stream-json',
      '--verbose',                       // required for stream-json output
      '--model', this.o.model,
      '--mcp-config', cfgPath,
      // WITHOUT THIS the router inherits the user's own MCP servers — 96 tools
      // and two failed connections, measured. Isolation is not a nicety here:
      // it is what keeps the tool surface at one.
      '--strict-mcp-config',
      '--permission-mode', 'bypassPermissions',
    ], { cwd: this.dir, stdio: ['pipe', 'pipe', 'pipe'], env: process.env })

    this.child = child
    this.buf = ''
    this.calls = []
    this.taken = 0
    this.decisions = 0
    this.ready = false

    child.stdout?.on('data', (d: Buffer) => this.onData(d.toString()))
    child.on('exit', (code) => {
      log.event('headless-exit', { code })
      if (this.child === child) { this.child = null; this.ready = false }
    })
    child.on('error', (e) => log.warn('headless spawn error', { error: e.message }))

    // Prime: make it load the tool schema now, on our time rather than the
    // user's. Also proves the whole chain is alive before a real utterance.
    this.send(`[Unmute router] Startup check. Load the ${QUALIFIED_TOOL} tool with ToolSearch so it is ready, then reply with the single word READY. Do not call it.`)
    const primed = await this.waitFor(() => this.ready, 60_000)
    log.event('headless-warm', { primed, model: this.o.model })
  }

  private onData(chunk: string): void {
    this.buf += chunk
    let i: number
    while ((i = this.buf.indexOf('\n')) >= 0) {
      const line = this.buf.slice(0, i)
      this.buf = this.buf.slice(i + 1)
      if (!line.trim()) continue
      let ev: Record<string, unknown>
      try { ev = JSON.parse(line) as Record<string, unknown> } catch { continue }

      if (ev.type === 'system' && ev.subtype === 'init') this.ready = true

      if (ev.type === 'assistant') {
        const msg = ev.message as { content?: Array<Record<string, unknown>> } | undefined
        for (const c of msg?.content ?? []) {
          if (c.type === 'tool_use' && String(c.name).endsWith(ROUTE_TOOL_NAME)) {
            this.calls.push(c.input)
          }
        }
      }
    }
  }

  private send(text: string): void {
    if (!this.child?.stdin?.writable) return
    // ONE LINE, ONE MESSAGE. No paste buffer, no confirming Enter, no sleep.
    this.child.stdin.write(JSON.stringify({
      type: 'user',
      message: { role: 'user', content: [{ type: 'text', text }] },
    }) + '\n')
  }

  private async waitFor(pred: () => boolean, ms: number): Promise<boolean> {
    const t0 = Date.now()
    while (Date.now() - t0 < ms) {
      if (pred()) return true
      if (!this.child || this.child.killed) return false
      await new Promise((r) => setTimeout(r, 40))
    }
    return false
  }

  /** Same signature as the Codex engine and the PTY path: a JSON string, or
   *  null to let the caller's failsafe run. */
  async decide(prompt: string, timeoutMs = 60_000): Promise<string | null> {
    await this.warm()
    if (!this.child || this.child.killed) return null

    const want = this.taken + 1
    const t0 = Date.now()
    // buildRoutingPrompt already opens with the tool instruction (it is told
    // via `answerTool`), so nothing is appended here. Keeping the instruction
    // in ONE place is what stops the two halves contradicting each other — the
    // shared prompt used to end with "no tools", which forbade the ToolSearch
    // this very call depends on.
    this.send(prompt)

    const got = await this.waitFor(() => this.calls.length >= want, timeoutMs)
    if (!got) {
      log.warn('headless router: no decision', { ms: Date.now() - t0 })
      return null
    }
    const args = this.calls[this.taken]
    this.taken = want
    const raw = compactDecision(args)
    log.event('headless-decision', { ms: Date.now() - t0, bytes: raw.length })

    if (++this.decisions >= this.o.recycleEvery) void this.recycle()
    return raw || null
  }

  /** Fresh process, off the hot path. No /clear to forget to submit. */
  private async recycle(): Promise<void> {
    log.event('headless-recycle', { decisions: this.decisions })
    const old = this.child
    this.child = null
    this.ready = false
    try { old?.kill() } catch { /* best-effort */ }
    await this.warm()
  }

  dispose(): void {
    try { this.child?.kill() } catch { /* best-effort */ }
    this.child = null
    this.ready = false
  }
}
