// THE CLAUDE ROUTER, WITHOUT A TERMINAL.
//
// Same prompt, same parser, same failsafe. What changes is the transport, and
// with it an entire class of bug — because the old one drove an interactive TUI
// through a PTY, which is a keyboard emulator:
//
//   * a 16KB prompt landed as a PASTE that sits one Enter short of submitting,
//     so we slept 450ms and sent \r and hoped. When the timing slipped the
//     Enter submitted an empty line, and the model said so out loud:
//     "both of your messages so far were empty (no content came through)".
//   * `/clear` was written the same way and never submitted at all, so context
//     never cleared and routing slowed from 15.9s to 24.0s across two turns.
//   * the trust dialog listed "No, exit" FIRST, so a stray Enter killed the
//     session; Enter is not \r anyway (kitty keyboard protocol).
//   * with no clean stdout, the answer had to come back through a FILE.
//
// None of that exists here. stdin is a PIPE: one newline-delimited JSON object
// is one message by framing, not by keystroke timing. There is nothing to
// confirm, nothing to poll, nothing to scrape out of escape sequences.
//
// MEASURED before it was written (28 Aug), because guessing is what produced
// the bugs above. Three routes down one warm process: 9.1s / 2.0s / 5.5s,
// against 15.9s and 24.0s on the PTY path — and the schema held every time.
//
// A PRIVATE, STDIO MCP SERVER
// ---------------------------
// The tool lives in a node process this engine spawns and owns, reachable only
// over that pipe. The alternative — a `router` principal on Unmute's shared
// HTTP MCP server — would have put a task-creating surface on a port, and the
// invariant that task sessions cannot touch the wall is worth more than the
// few lines it saves. Nothing but this engine can reach this tool.
//
// THE TOOLSEARCH HOP, which cost three failed spike runs to find: the tool is
// DEFERRED — the model must call ToolSearch to load its schema before it can
// call it. A prompt that says "reply ONLY by calling the tool, do nothing else"
// forbids exactly that, and the route then silently never happens. So the
// prompt permits it, and warm() pays for it ONCE per process (that is the
// difference between the 9.1s first turn and the 2.0s second).

import { spawn, type ChildProcess } from 'node:child_process'
import { promises as fs } from 'node:fs'
import { join } from 'node:path'
import { homedir } from 'node:os'
import { createLogger } from './log'
import { devEvent } from './curator-devlog'
import { routeDecisionTool, compactDecision, ROUTE_TOOL_NAME, type DecisionSchemaOpts } from './router-decision-schema'

const log = createLogger('headless-router')

/** Fully-qualified name Claude gives an MCP tool: mcp__<server>__<tool>. */
const SERVER = 'unmute_router'
export const QUALIFIED_TOOL = `mcp__${SERVER}__${ROUTE_TOOL_NAME}`

export interface HeadlessRouterOpts {
  model?: string
  /** Where the generated MCP server + config are written. */
  dir?: string
  /** Respawn after this many decisions, to cap context growth. */
  recycleEvery?: number
  /** Test seam. */
  spawnFn?: typeof spawn
  execPath?: string
}

/**
 * The one-tool MCP server, written to disk at warm() time.
 *
 * Generated rather than shipped as a file because the app is packaged into an
 * asar, which an external node process cannot execute out of. It is ~40 lines
 * and has no dependencies, so generating it is cheaper than unpacking it.
 *
 * It does NOT need to do anything with the arguments: the decision is read off
 * the CLI's own event stream (a `tool_use` block on stdout), not from here.
 * This server exists purely to put a JSON Schema in front of the model. Its
 * stderr never reaches us — it is the CLI's child, not ours, which cost one
 * spike run to discover.
 */
function serverSource(tool: ReturnType<typeof routeDecisionTool>): string {
  return `// Generated by Unmute. One schema'd tool; the decision is read from the CLI stream.
const TOOL = ${JSON.stringify(tool, null, 2)}
const send = (o) => process.stdout.write(JSON.stringify(o) + '\\n')
let buf = ''
process.stdin.on('data', (d) => {
  buf += d
  let i
  while ((i = buf.indexOf('\\n')) >= 0) {
    const line = buf.slice(0, i); buf = buf.slice(i + 1)
    if (!line.trim()) continue
    let m; try { m = JSON.parse(line) } catch { continue }
    if (m.method === 'initialize') {
      send({ jsonrpc: '2.0', id: m.id, result: {
        protocolVersion: (m.params && m.params.protocolVersion) || '2024-11-05',
        capabilities: { tools: {} },
        serverInfo: { name: '${SERVER}', version: '1.0.0' },
      } })
    } else if (m.method === 'tools/list') {
      send({ jsonrpc: '2.0', id: m.id, result: { tools: [TOOL] } })
    } else if (m.method === 'tools/call') {
      send({ jsonrpc: '2.0', id: m.id, result: { content: [{ type: 'text', text: 'recorded' }] } })
    } else if (m.id !== undefined) {
      send({ jsonrpc: '2.0', id: m.id, result: {} })
    }
  }
})
`
}

export class HeadlessRouterEngine {
  /** Declared to the Router so the prompt asks for a TOOL CALL and, crucially,
   *  stops telling the model "no tools" — which would forbid loading this one. */
  /** Name for the router's logs. */
  readonly label = 'claude-headless'
  readonly answerTool = QUALIFIED_TOOL
  private child: ChildProcess | null = null
  private buf = ''
  /** Decisions seen on the stream, oldest first; decide() takes the next one. */
  private calls: unknown[] = []
  private taken = 0
  private ready = false
  private decisions = 0
  private starting: Promise<void> | null = null
  // WHAT HAPPENED DURING THIS ROUTE. The failure modes here are all SILENT —
  // the model answers in prose, or never loads the tool, or the MCP server
  // never connected — and each looks identical from outside: a timeout. These
  // fields are what turn "it didn't work" into a named cause in the log.
  private sawToolSearch = false
  private sawText: string[] = []
  private lastResult: Record<string, unknown> | null = null
  private stderrTail: string[] = []
  private readonly dir: string
  private readonly o: Required<Omit<HeadlessRouterOpts, 'spawnFn' | 'execPath' | 'dir'>> & Pick<HeadlessRouterOpts, 'spawnFn' | 'execPath'>

  constructor(opts: HeadlessRouterOpts = {}, private readonly schemaOpts: DecisionSchemaOpts = { ops: true }) {
    this.dir = opts.dir ?? join(homedir(), '.unmute', 'remote', 'router-headless')
    this.o = {
      model: opts.model ?? 'sonnet',
      recycleEvery: opts.recycleEvery ?? 40,
      spawnFn: opts.spawnFn,
      execPath: opts.execPath,
    }
  }

  /** Bring a process up AND load the tool schema into it, so the first real
   *  route does not pay the ToolSearch hop. Idempotent and single-flighted. */
  warm(): Promise<void> {
    if (this.ready && this.child && !this.child.killed) return Promise.resolve()
    if (this.starting) return this.starting
    this.starting = this.start().catch((e) => {
      log.warn('headless router failed to warm', { error: (e as Error).message })
    }).finally(() => { this.starting = null })
    return this.starting
  }

  private async start(): Promise<void> {
    await fs.mkdir(this.dir, { recursive: true })
    const serverPath = join(this.dir, 'router-mcp.mjs')
    const cfgPath = join(this.dir, 'mcp.json')
    const exec = this.o.execPath ?? process.execPath
    await fs.writeFile(serverPath, serverSource(routeDecisionTool(this.schemaOpts)))
    await fs.writeFile(cfgPath, JSON.stringify({
      mcpServers: {
        [SERVER]: {
          command: exec,
          args: [serverPath],
          // Electron's binary IS node when this is set; a packaged build has no
          // system node to rely on.
          env: { ELECTRON_RUN_AS_NODE: '1' },
        },
      },
    }))

    const sp = this.o.spawnFn ?? spawn
    const child = sp('claude', [
      '-p',
      '--input-format', 'stream-json',
      '--output-format', 'stream-json',
      '--verbose',                       // required for stream-json output
      '--model', this.o.model,
      '--mcp-config', cfgPath,
      // WITHOUT THIS the router inherits the user's own MCP servers — 96 tools
      // and two failed connections, measured. Isolation is not a nicety here:
      // it is what keeps the tool surface at one.
      '--strict-mcp-config',
      '--permission-mode', 'bypassPermissions',
    ], { cwd: this.dir, stdio: ['pipe', 'pipe', 'pipe'], env: process.env })

    log.event('headless-spawn', {
      model: this.o.model, dir: this.dir, exec,
      argv: ['claude', '-p', '--input-format stream-json', '--output-format stream-json',
             '--mcp-config', '--strict-mcp-config', '--permission-mode bypassPermissions'].join(' '),
    })

    this.child = child
    this.buf = ''
    this.calls = []
    this.taken = 0
    this.decisions = 0
    this.ready = false

    child.stdout?.on('data', (d: Buffer) => this.onData(d.toString()))
    // STDERR WAS BEING DROPPED ENTIRELY. When the CLI refuses to start — bad
    // flag, auth expired, model unavailable — this is the ONLY place it says
    // so, and without it the symptom is an unexplained warm timeout.
    child.stderr?.on('data', (d: Buffer) => {
      const t = d.toString().trim()
      if (!t) return
      this.stderrTail = [...this.stderrTail, t].slice(-6)
      log.warn('headless stderr', { line: t.slice(0, 400) })
    })
    child.on('exit', (code, signal) => {
      log.event('headless-exit', { code, signal, decisions: this.decisions })
      if (this.child === child) { this.child = null; this.ready = false }
    })
    child.on('error', (e) => log.warn('headless spawn error', { error: e.message }))

    // Prime: make it load the tool schema now, on our time rather than the
    // user's. Also proves the whole chain is alive before a real utterance.
    this.send(`[Unmute router] Startup check. Load the ${QUALIFIED_TOOL} tool with ToolSearch so it is ready, then reply with the single word READY. Do not call it.`)
    const tw = Date.now()
    const primed = await this.waitFor(() => this.ready, 60_000)
    // `primed:false` here is the single highest-value line in this file: it
    // means the CLI never even reached init, so every route after it will time
    // out. Pair it with headless-mcp-status and headless-stderr for the cause.
    log.event('headless-warm', {
      primed, ms: Date.now() - tw, model: this.o.model,
      toolSearchUsed: this.sawToolSearch, stderr: this.stderrTail.slice(-2),
    })
  }

  private onData(chunk: string): void {
    this.buf += chunk
    let i: number
    while ((i = this.buf.indexOf('\n')) >= 0) {
      const line = this.buf.slice(0, i)
      this.buf = this.buf.slice(i + 1)
      if (!line.trim()) continue
      let ev: Record<string, unknown>
      try { ev = JSON.parse(line) as Record<string, unknown> } catch { continue }

      if (ev.type === 'system' && ev.subtype === 'init') {
        this.ready = true
        // THE HANDSHAKE, AND WHETHER OUR TOOL SURVIVED IT. If the server shows
        // anything but "connected", or the tool is missing, every route will
        // time out with no other explanation anywhere. Measured once already:
        // without --strict-mcp-config this listed 96 tools and two failed
        // servers instead of one clean connection.
        const tools = (ev.tools as string[] | undefined) ?? []
        log.event('headless-mcp-status', {
          servers: ev.mcp_servers ?? null,
          toolVisible: tools.some((t) => t.endsWith(ROUTE_TOOL_NAME)),
          totalTools: tools.length,
        })
      }

      if (ev.type === 'assistant') {
        const msg = ev.message as { content?: Array<Record<string, unknown>> } | undefined
        for (const c of msg?.content ?? []) {
          if (c.type === 'tool_use') {
            const nm = String(c.name)
            // The deferred-schema hop. Seeing it is normal on a cold process
            // and is what warm() exists to pay for; NOT seeing it before a
            // timeout means the model was never able to load the tool.
            if (nm === 'ToolSearch') {
              this.sawToolSearch = true
              log.event('headless-toolsearch', { query: (c.input as { query?: string } | undefined)?.query ?? null })
            }
            if (nm.endsWith(ROUTE_TOOL_NAME)) this.calls.push(c.input)
          }
          // PROSE INSTEAD OF A TOOL CALL — the failure that has bitten us twice
          // on the old transport ("your message got cut off", a conversational
          // answer about work being on hold). Recording the model's own words
          // is the difference between a named cause and a shrug.
          if (c.type === 'text') {
            const t = String(c.text ?? '').trim()
            if (t) {
              this.sawText.push(t)
              devEvent(log, 'headless-assistant-text', { text: t.slice(0, 600) })
            }
          }
        }
      }

      if (ev.type === 'result') {
        this.lastResult = {
          subtype: ev.subtype ?? null,
          durationMs: ev.duration_ms ?? null,
          numTurns: ev.num_turns ?? null,
          isError: ev.is_error ?? null,
        }
        log.event('headless-result', this.lastResult)
      }
    }
  }

  private send(text: string): void {
    if (!this.child?.stdin?.writable) return
    // ONE LINE, ONE MESSAGE. No paste buffer, no confirming Enter, no sleep.
    this.child.stdin.write(JSON.stringify({
      type: 'user',
      message: { role: 'user', content: [{ type: 'text', text }] },
    }) + '\n')
  }

  private async waitFor(pred: () => boolean, ms: number): Promise<boolean> {
    const t0 = Date.now()
    while (Date.now() - t0 < ms) {
      if (pred()) return true
      if (!this.child || this.child.killed) return false
      await new Promise((r) => setTimeout(r, 40))
    }
    return false
  }

  /** Same signature as the Codex engine and the PTY path: a JSON string, or
   *  null to let the caller's failsafe run. */
  async decide(prompt: string, timeoutMs = 60_000): Promise<string | null> {
    await this.warm()
    if (!this.child || this.child.killed) return null

    const want = this.taken + 1
    const t0 = Date.now()
    // Per-route trace resets, so a failure line describes THIS route and not a
    // previous one's leftovers.
    this.sawText = []
    this.lastResult = null
    log.event('headless-route-start', {
      promptBytes: Buffer.byteLength(prompt), timeoutMs,
      decisionsThisProcess: this.decisions, toolAlreadyLoaded: this.sawToolSearch,
    })
    // buildRoutingPrompt already opens with the tool instruction (it is told
    // via `answerTool`), so nothing is appended here. Keeping the instruction
    // in ONE place is what stops the two halves contradicting each other — the
    // shared prompt used to end with "no tools", which forbade the ToolSearch
    // this very call depends on.
    this.send(prompt)

    const got = await this.waitFor(() => this.calls.length >= want, timeoutMs)
    if (!got) {
      // NAME THE CAUSE. These four fields separate the failures that used to
      // look identical from outside:
      //   alive:false                  the CLI died (see headless-stderr/exit)
      //   toolSearchUsed:false         it never loaded the tool - the prompt
      //                                probably forbade it
      //   assistantText present        it ANSWERED, in prose, instead of
      //                                calling the tool - the words are here
      //   result present, no call      it finished its turn and simply chose
      //                                not to call the tool
      log.warn('headless router: no decision', {
        ms: Date.now() - t0,
        alive: !!this.child && !this.child.killed,
        toolSearchUsed: this.sawToolSearch,
        assistantText: this.sawText.slice(-2).map((t) => t.slice(0, 300)),
        result: this.lastResult,
        stderr: this.stderrTail.slice(-2),
      })
      return null
    }
    const args = this.calls[this.taken]
    this.taken = want
    const raw = compactDecision(args)
    // THE DECISION ITSELF, not a byte count. This is the line that answers
    // "why did my task get that name / land in that group", which is the
    // question every grouping complaint so far has actually been.
    const d = (args ?? {}) as Record<string, unknown>
    log.event('headless-decision', {
      ms: Date.now() - t0,
      action: d.action ?? null, name: d.name ?? null, group: d.group ?? null,
      kind: d.kind ?? null, mode: d.mode ?? null, dir: d.dir ?? null,
      targetTaskId: d.targetTaskId ?? null, surface: d.surface ?? null,
      spokeFirst: this.sawText.length > 0,   // prose alongside the call
      turns: this.lastResult?.numTurns ?? null,
    })
    devEvent(log, 'headless-decision-raw', { raw })

    if (++this.decisions >= this.o.recycleEvery) void this.recycle()
    return raw || null
  }

  /** Fresh process, off the hot path. No /clear to forget to submit. */
  private async recycle(): Promise<void> {
    log.event('headless-recycle', { decisions: this.decisions })
    const old = this.child
    this.child = null
    this.ready = false
    try { old?.kill() } catch { /* best-effort */ }
    await this.warm()
  }

  dispose(): void {
    try { this.child?.kill() } catch { /* best-effort */ }
    this.child = null
    this.ready = false
  }
}
